# Generated by Django 2.2.1 on 2022-07-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='imgs_from_posts/default.jpg', upload_to='imgs_from_posts'),
        ),
    ]
