# Generated by Django 4.0.6 on 2022-07-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Обмен', 'verbose_name_plural': 'Обмены'},
        ),
    ]
