# Generated by Django 4.0.6 on 2022-07-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='task',
            new_name='tasks',
        ),
    ]
